In [1]:
# 我们要定位文件位置，使用这里的代码，具体要将此notebook文件和function文件（或文件夹）放在同一个文件夹路径下，具体路径是什么可以左侧找到目标文件夹然后右击复制文件夹路径来获得
import sys
sys.path.insert(0,'/content/drive/MyDrive/JPMorgan/自写代码/TensorFlow_codes')

In [3]:
# Pip install pandas_datareader
%pip install pandas_datareader
%pip install --upgrade pandas
%pip install --upgrade pandas_datareader
%pip install yfinance

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: pandas_datareader in /usr/local/lib/python3.8/dist-packages (0.9.0)
Requirement already satisfied: pandas>=0.23 in /usr/local/lib/python3.8/dist-packages (from pandas_datareader) (1.3.5)
Requirement already satisfied: requests>=2.19.0 in /usr/local/lib/python3.8/dist-packages (from pandas_datareader) (2.25.1)
Requirement already satisfied: lxml in /usr/local/lib/python3.8/dist-packages (from pandas_datareader) (4.9.2)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.8/dist-packages (from pandas>=0.23->pandas_datareader) (2022.7)
Requirement already satisfied: numpy>=1.17.3 in /usr/local/lib/python3.8/dist-packages (from pandas>=0.23->pandas_datareader) (1.21.6)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.8/dist-packages (from pandas>=0.23->pandas_datareader) (2.8.2)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.8/dist-packages (from requests>=2.19.0->pandas_datareader) (1.24.3)
Requirement already satisfied: chardet<5,>=3.0.2 in /usr/local/lib/python3.8/dist-packages (from requests>=2.19.0->pandas_datareader) (4.0.0)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.8/dist-packages (from requests>=2.19.0->pandas_datareader) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.8/dist-packages (from requests>=2.19.0->pandas_datareader) (2022.12.7)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.7.3->pandas>=0.23->pandas_datareader) (1.15.0)
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (1.3.5)
Collecting pandas
  Downloading pandas-1.5.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.2/12.2 MB 63.8 MB/s eta 0:00:00
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2022.7)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: numpy>=1.20.3 in /usr/local/lib/python3.8/dist-packages (from pandas) (1.21.6)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.1->pandas) (1.15.0)
Installing collected packages: pandas
  Attempting uninstall: pandas
    Found existing installation: pandas 1.3.5
    Uninstalling pandas-1.3.5:
      Successfully uninstalled pandas-1.3.5
Successfully installed pandas-1.5.3

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: pandas_datareader in /usr/local/lib/python3.8/dist-packages (0.9.0)
Collecting pandas_datareader
  Downloading pandas_datareader-0.10.0-py3-none-any.whl (109 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 109.5/109.5 KB 6.6 MB/s eta 0:00:00
Requirement already satisfied: requests>=2.19.0 in /usr/local/lib/python3.8/dist-packages (from pandas_datareader) (2.25.1)
Requirement already satisfied: pandas>=0.23 in /usr/local/lib/python3.8/dist-packages (from pandas_datareader) (1.5.3)
Requirement already satisfied: lxml in /usr/local/lib/python3.8/dist-packages (from pandas_datareader) (4.9.2)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.8/dist-packages (from pandas>=0.23->pandas_datareader) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas>=0.23->pandas_datareader) (2022.7)
Requirement already satisfied: numpy>=1.20.3 in /usr/local/lib/python3.8/dist-packages (from pandas>=0.23->pandas_datareader) (1.21.6)
Requirement already satisfied: chardet<5,>=3.0.2 in /usr/local/lib/python3.8/dist-packages (from requests>=2.19.0->pandas_datareader) (4.0.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.8/dist-packages (from requests>=2.19.0->pandas_datareader) (2022.12.7)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.8/dist-packages (from requests>=2.19.0->pandas_datareader) (2.10)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.8/dist-packages (from requests>=2.19.0->pandas_datareader) (1.24.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.1->pandas>=0.23->pandas_datareader) (1.15.0)
Installing collected packages: pandas_datareader
  Attempting uninstall: pandas_datareader
    Found existing installation: pandas-datareader 0.9.0
    Uninstalling pandas-datareader-0.9.0:
      Successfully uninstalled pandas-datareader-0.9.0
Successfully installed pandas_datareader-0.10.0

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting yfinance
  Downloading yfinance-0.2.9-py2.py3-none-any.whl (55 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 55.9/55.9 KB 3.0 MB/s eta 0:00:00
Requirement already satisfied: pytz>=2022.5 in /usr/local/lib/python3.8/dist-packages (from yfinance) (2022.7)
Collecting cryptography>=3.3.2
  Downloading cryptography-39.0.0-cp36-abi3-manylinux_2_28_x86_64.whl (4.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 62.1 MB/s eta 0:00:00
Requirement already satisfied: pandas>=1.3.0 in /usr/local/lib/python3.8/dist-packages (from yfinance) (1.5.3)
Requirement already satisfied: numpy>=1.16.5 in /usr/local/lib/python3.8/dist-packages (from yfinance) (1.21.6)
Requirement already satisfied: lxml>=4.9.1 in /usr/local/lib/python3.8/dist-packages (from yfinance) (4.9.2)
Requirement already satisfied: appdirs>=1.4.4 in /usr/local/lib/python3.8/dist-packages (from yfinance) (1.4.4)
Collecting html5lib>=1.1
  Downloading html5lib-1.1-py2.py3-none-any.whl (112 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 112.2/112.2 KB 15.3 MB/s eta 0:00:00
Collecting beautifulsoup4>=4.11.1
  Downloading beautifulsoup4-4.11.2-py3-none-any.whl (129 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 129.4/129.4 KB 16.5 MB/s eta 0:00:00
Collecting frozendict>=2.3.4
  Downloading frozendict-2.3.4-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (110 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 111.0/111.0 KB 16.3 MB/s eta 0:00:00
Requirement already satisfied: multitasking>=0.0.7 in /usr/local/lib/python3.8/dist-packages (from yfinance) (0.0.11)
Collecting requests>=2.26
  Downloading requests-2.28.2-py3-none-any.whl (62 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.8/62.8 KB 9.3 MB/s eta 0:00:00
Collecting soupsieve>1.2
  Downloading soupsieve-2.3.2.post1-py3-none-any.whl (37 kB)
Requirement already satisfied: cffi>=1.12 in /usr/local/lib/python3.8/dist-packages (from cryptography>=3.3.2->yfinance) (1.15.1)
Requirement already satisfied: six>=1.9 in /usr/local/lib/python3.8/dist-packages (from html5lib>=1.1->yfinance) (1.15.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.8/dist-packages (from html5lib>=1.1->yfinance) (0.5.1)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.8/dist-packages (from pandas>=1.3.0->yfinance) (2.8.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.8/dist-packages (from requests>=2.26->yfinance) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.8/dist-packages (from requests>=2.26->yfinance) (2022.12.7)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.8/dist-packages (from requests>=2.26->yfinance) (2.1.1)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.8/dist-packages (from requests>=2.26->yfinance) (1.24.3)
Requirement already satisfied: pycparser in /usr/local/lib/python3.8/dist-packages (from cffi>=1.12->cryptography>=3.3.2->yfinance) (2.21)
Installing collected packages: soupsieve, requests, html5lib, frozendict, cryptography, beautifulsoup4, yfinance
  Attempting uninstall: requests
    Found existing installation: requests 2.25.1
    Uninstalling requests-2.25.1:
      Successfully uninstalled requests-2.25.1
  Attempting uninstall: html5lib
    Found existing installation: html5lib 1.0.1
    Uninstalling html5lib-1.0.1:
      Successfully uninstalled html5lib-1.0.1
  Attempting uninstall: beautifulsoup4
    Found existing installation: beautifulsoup4 4.6.3
    Uninstalling beautifulsoup4-4.6.3:
      Successfully uninstalled beautifulsoup4-4.6.3
Successfully installed beautifulsoup4-4.11.2 cryptography-39.0.0 frozendict-2.3.4 html5lib-1.1 requests-2.28.2 soupsieve-2.3.2.post1 yfinance-0.2.9

In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import pandas_datareader.data as web
import yfinance as yfin
#from pandas_datareader import data as pdr
import datetime as dt

In [4]:
# We set the time range from 2013/01/23 to 2023/1/23, the whole 10 year.
import datetime as dt
start = dt.datetime(2013,1,23)
end=dt.datetime(2023,1,23)

start

datetime.datetime(2013, 1, 23, 0, 0)

[Section 1]: Dow Jones 30

List:

(1) American Express (axp)

(2) Amgen (amgn)

(3) Apple (aapl)

(4) Boeing (ba)

(5) Caterpillar (cat)

(6) Chevron (cvx)

(7) Cisco Systems (csco) 

(8) Coca-Cola (ko)

(9) Dow, Inc. (dow)

(10) Goldman Sachs (gs)

(11) Home Depot (hd)

(12) Honeywell International (hon)

(13) Intel (intc)

(14) International Business Machines (ibm)

(15) Johnson & Johnson (jnj)

(16) JPMorgan Chase (jpm)

(17) McDonald's (mcd)

(18) 3M (mmm)

(19) Merck (mrk)

(20) Microsoft (msft)

(21) Nike (nke)

(22) Procter & Gamble (pg)

(23) Salesforce.com (crm)

(24) Travelers (trv)

(25) UnitedHealth Group (unh)

(26) Verizon (vz)

(27) Visa (v)

(28) Walgreens Boots Alliance (wba)

(29) Walmart (wmt)

(30) Walt Disney (dis)

In [6]:
yfin.pdr_override()
stocks = ['axp', 'amgn', 'aapl','ba', 'cat', 'cvx', 'csco', 'ko', 'dow', 'gs', 'hd', 'hon', 'intc', 'ibm', \
          'jnj', 'jpm', 'mcd', 'mmm', 'mrk', 'msft', 'nke', 'pg', 'crm', 'trv', 'unh', 'vz', 'v', 'wba', 'wmt', 'dis']
ls_key = 'Adj Close' 
ls_key_data = []
for stock in stocks:
  df_dow_original = web.get_data_yahoo(stock,start,end)
  ls_key_data.append(df_dow_original[ls_key])

df_dow = pd.DataFrame(columns = stocks, index = df_dow_original.index)
for i in range(len(stocks)):
  stock = stocks[i]
  df_dow[stock] = ls_key_data[i]

# We drop the stocks which don't have 10-year's historical data, if one stock doesn't have sufficient 10-year data then the first data would be np.nan. 
# We drop this stock based on this judgement.
for j in df_dow.columns:
  if np.isnan(df_dow[j][0]) == True:
    df_dow = df_dow.drop(j,axis = 1)
#clean_data = df_dow.ix[ls_key]
#df_dow = pd.DataFrame(clean_data)
df_dow

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

,axp,amgn,aapl,ba,cat,cvx,csco,ko,gs,hd,...,nke,pg,crm,trv,unh,vz,v,wba,wmt,dis
Date,,,,,,,,,,,,,,,,,,,,,
2013-01-23 00:00:00-05:00,51.051548,64.127632,15.787227,62.254246,73.055489,76.055016,15.086037,27.105654,122.984009,53.134556,...,23.758385,52.821316,42.605000,61.582077,47.942146,27.051647,37.082520,29.898693,55.654446,49.045555
2013-01-24 00:00:00-05:00,51.372089,63.780251,13.836591,63.117355,72.866913,76.379051,15.378683,27.091053,122.477074,53.846088,...,24.102976,52.619572,43.072498,61.939030,48.207966,26.925205,37.201420,29.838169,55.894703,49.045555
2013-01-25 00:00:00-05:00,51.545361,64.397827,13.510408,62.874371,72.097519,76.841957,15.473796,27.047247,122.054626,54.221878,...,24.859262,54.734203,43.465000,62.145237,48.053612,26.975786,37.266712,30.012180,55.262016,49.436470
2013-01-28 00:00:00-05:00,51.172844,66.073021,13.816008,62.011215,73.508087,76.736176,15.407951,27.018044,121.792709,54.030006,...,24.389376,55.122768,44.517502,61.352058,47.856403,27.039007,36.453011,30.337492,55.542309,49.418289
2013-01-29 00:00:00-05:00,51.502026,66.844978,14.075231,61.717937,74.375572,77.509880,15.203097,27.317358,124.285187,53.726181,...,24.129818,56.041859,43.672501,61.716923,48.259407,27.500498,36.525291,30.307240,55.974819,49.081928
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-01-13 00:00:00-05:00,155.759995,271.730011,134.759995,214.130005,257.233215,177.559998,48.880001,61.430000,374.000000,331.209991,...,128.850006,149.939133,149.509995,193.919998,489.570007,41.860001,223.059998,36.779999,145.289993,99.400002
2023-01-17 00:00:00-05:00,153.750000,269.420013,135.940002,211.410004,255.043686,180.490005,48.080002,61.680000,349.920013,327.529999,...,128.139999,149.501877,148.470001,185.000000,485.079987,40.849998,223.000000,36.330002,144.410004,99.910004
2023-01-18 00:00:00-05:00,150.419998,264.390015,135.210007,209.410004,251.620010,177.229996,46.900002,59.810001,349.089996,323.690002,...,126.430000,145.497009,145.449997,183.630005,476.239990,39.970001,219.460007,35.610001,140.839996,99.040001
2023-01-19 00:00:00-05:00,146.850006,262.029999,135.270004,207.089996,245.750000,179.000000,46.459999,59.720001,350.750000,310.880005,...,124.529999,142.419998,146.410004,184.039993,484.359985,40.060001,220.410004,35.410000,138.830002,99.080002
2023-01-20 00:00:00-05:00,151.600006,263.239990,137.869995,206.759995,249.710007,180.899994,46.779999,60.080002,341.839996,315.000000,...,126.620003,142.970001,151.250000,185.330002,486.720001,40.000000,224.309998,35.880001,140.539993,103.480003

In [41]:
# Save the generated Dow 30data

df_dow.to_csv('/content/drive/MyDrive/JPMorgan/自写代码/TensorFlow_codes/Stock_datas/dow30_data.csv')

[Section2]: EuroStoxx 50

List

(1) AB InBev (BUD)

(2) adidas (ADS.DE)

(3) Adyen B.V. Parts Sociales (ADYEN.AS)

(4) Ahold Delhaize (AD.AS)

(5) Air Liquide (AI.PA)

(6) Airbus (AIR.PA)

(7) Allianz (ALV.DE)

(8) ASML NV (ASML)

(9) AXA (CS.PA)

(10) BASF (BAS.DE)

(11) Bayer (BAYZF)

(12) BBVA (BBVA)

(13) BMW (BMW.DE)

(14) BNP Paribas (BNP.PA)

(15) CRH (CRH)

(16) Danone (BN.PA)

(17) Deutsche Börse (DB1.DE)

(18) Deutsche Post (DPW.DE)

(19) Deutsche Telekom (DTE.DE)

(20) Enel (ENL.DE)

(21) Eni (E)

(22) EssilorLuxottica (EL.PA)

(23) Flutter Entertainment (PDYPY)

(24) Iberdrola (IBDRY)

(25) Inditex (IDEXY)

(26) Infineon (IFX.DE)

(27) ING Group (ING)

(28) Intesa Sanpaolo (ISP.MI)

(29) Kering (KER.PA)

(30) Linde (LIN)

(31) L'Oréal (OR.PA)

(32) LVMH Moet Hennessy Louis Vuitton (LVMUY)

(33) Mercedes-Benz Group (MBG.DE)

(34) Münchener Rückversicherungs-Gesellschaft (MUV2.MI)

(35) Nokia (NOK)

(36) Nordea Bank Abp Registered Shs (NDA-FI.HE)

(37) Pernod Ricard (PRNDY)

(38) Prosus (PRX.AS)

(39) SAFRAN (SEJ1.SG)

(40) Sanofi (SNW.SG)

(41) Santander (SAN)

(42) SAP (SAP)

(43) Schneider Electric (SU.PA)

(44) Siemens (SIE.DE)

(45) Stellantis (STLA)

(46) TotalEnergies (TTFNF)

(47) VINCI (DG.PA)

(48) Volkswagen (VOW3.DE)

(49) Vonovia (VNA.DE)

In [5]:
yfin.pdr_override()
stocks2 = ['BUD', 'ADS.DE', 'ADYEN.AS','AD.AS', 'AI.PA', 'AIR.PA', 'ALV.DE', 'ASML', 'CS.PA', 'BAS.DE', 'BAYZF', 'BBVA', 'BMW.DE', 'BNP.PA', \
          'CRH', 'BN.PA', 'DB1.DE', 'DPW.DE', 'DTE.DE', 'ENL.DE', 'E', 'EL.PA', 'PDYPY', 'IBDRY', 'IDEXY', 'IFX.DE', 'ING', 'ISP.MI', 'KER.PA', 'LIN', \
           'OR.PA', 'LVMUY', 'MBG.DE', 'MUV2.MI', 'NOK', 'NDA-FI.HE', 'PRNDY', 'PRX.AS', 'SEJ1.SG', 'SNW.SG', 'SAN', 'SAP', 'SU.PA', 'SIE.DE', 'STLA', \
           'TTFNF', 'DG.PA', 'VOW3.DE', 'VNA.DE']
ls_key = 'Adj Close' 
ls_key_data = []
for stock in stocks2:
  df_stoxx_original = web.get_data_yahoo(stock,start,end)
  ls_key_data.append(df_stoxx_original[ls_key])

df_stoxx = pd.DataFrame(columns = stocks2)
for i in range(len(stocks2)):
  stock = stocks2[i]
  df_stoxx[stock] = ls_key_data[i]

# We drop the stocks which don't have 10-year's historical data, if one stock doesn't have sufficient 10-year data then the first data would be np.nan. 
# We drop this stock based on this judgement.
for j in df_stoxx.columns:
  if np.isnan(df_stoxx[j][0]) == True:
    df_stoxx = df_stoxx.drop(j,axis = 1)

df_stoxx

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

,BUD,ASML,BAYZF,BBVA,CRH,E,IBDRY,IDEXY,ING,LIN,LVMUY,NOK,PRNDY,SAN,SAP,STLA,TTFNF
Date,,,,,,,,,,,,,,,,,
2013-01-23 00:00:00-05:00,70.186897,62.611176,73.488098,6.486995,15.476578,29.142651,13.439261,11.278678,6.522679,90.535728,27.143465,3.646603,20.270298,5.326166,66.550735,2.601512,37.866943
2013-01-24 00:00:00-05:00,70.295929,64.374489,73.298210,6.588650,16.136135,29.086239,13.602848,11.278678,6.596954,90.821823,27.550247,3.347959,20.453667,5.363498,66.449158,2.717532,37.866943
2013-01-25 00:00:00-05:00,71.425201,66.951637,73.298210,6.696662,16.320194,29.221621,14.043269,11.380891,6.677981,91.320366,28.104946,3.300804,20.712048,5.481720,68.556908,2.771079,38.826237
2013-01-28 00:00:00-05:00,71.503098,68.244743,77.361877,6.645834,16.258846,29.238550,13.804186,11.046736,6.779265,89.890053,27.994011,3.340100,20.378653,5.456831,68.023628,2.833552,38.335770
2013-01-29 00:00:00-05:00,72.616791,68.063881,75.417389,6.607711,16.381556,28.302109,13.967772,10.936660,6.765760,90.355927,28.134533,3.308664,20.695375,5.438165,68.751595,2.860325,39.165234
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-01-13 00:00:00-05:00,60.919998,659.690002,62.110001,6.890000,45.639999,31.450001,47.369999,14.940000,13.700000,334.109985,171.000000,5.030000,42.110001,3.370000,117.010002,15.420000,63.990002
2023-01-17 00:00:00-05:00,61.070000,658.190002,61.740002,6.930000,45.330002,31.129999,47.049999,14.910000,13.430000,330.000000,171.470001,4.820000,42.459999,3.330000,116.209999,15.450000,64.849998
2023-01-18 00:00:00-05:00,59.290001,652.289978,60.439999,6.880000,44.720001,30.990000,46.430000,14.860000,13.230000,324.339996,172.050003,4.780000,41.040001,3.330000,117.080002,15.280000,64.250000
2023-01-19 00:00:00-05:00,59.330002,630.250000,60.250000,6.810000,44.439999,31.219999,46.959999,14.690000,13.200000,324.540009,168.309998,4.680000,41.799999,3.290000,115.669998,15.130000,62.959999
2023-01-20 00:00:00-05:00,59.799999,648.849976,60.750000,6.910000,45.009998,31.709999,47.220001,14.900000,13.380000,328.619995,170.020004,4.610000,41.689999,3.350000,117.120003,15.200000,62.990002

In [6]:
# Save the generated EuroStoxx 50data

df_stoxx.to_csv('/content/drive/MyDrive/JPMorgan/自写代码/TensorFlow_codes/Stock_datas/stoxx50_data.csv')

**[Section3]: Hang Seng**

List

(1) CKH HOLDINGS (0001.HK)

(2) CLP HOLDINGS (00002.HK)

(3) HK & CHINA GAS (00003.HK)

(4) HSBC HOLDINGS (00005.HK)

(5) POWER ASSETS (00006.HK)

(6) HANG SENG BANK (00011.HK)

(7) HENDERSON LAND (00012.HK)

(8) SHK PPT	(00016.HK)

(9) NEW WORLD DEV (00017.HK)

(10) GALAXY ENT (00027.HK)

(11) MTR CORPORATION (00066.HK)

(12) HANG LUNG PPT (00101.HK)

(13) GEELY AUTO (00175.HK)

(14) ALI HEALTH (00241.HK)

(15) CITIC (00267.HK)

(16) WH GROUP (00288.HK)

(17) CHINA RES BEER (00291.HK)

(18) OOIL (00316.HK)

(19) TINGYI (00322.HK)

(20) SINOPEC CORP (00386.HK)

(21) HKEX	(00388.HK)

(22) TECHTRONIC IND (00669.HK)

(23) CHINA OVERSEAS (00688.HK)

(24) TENCENT (00700.HK)

(25) CHINA UNICOM (00762.HK)

(26) LINK REIT (00823.HK)

(27) PETROCHINA (00857.HK)

(28) XINYI GLASS (00868.HK)

(29) ZHONGSHENG HLDG (00881.HK)

(30) CNOOC (00883.HK)

(31) CCB (00939.HK)

(32) CHINA MOBILE (00941.HK)

(33) LONGFOR GROUP (00960.HK)

(34) XINYI SOLAR (00968.HK)

(35) SMIC (00981.HK)

(36) LENOVO GROUP (00992.HK)

(37) CKI HOLDINGS (01038.HK)

(38) HENGAN INT'L (01044.HK)

(39) CHINA SHENHUA (01088.HK)

(40) CSPC PHARMA (01093.HK)

(41) CHINA RES LAND (01109.HK)

(42) CK ASSET (01113.HK)

(43) SINO BIOPHARM (01177.HK)

(44) CHINA RES MIXC (01209.HK)

(45) BYD COMPANY (01211.HK)

(46) AIA (01299.HK)

(47) CHINAHONGQIAO (01378.HK)

(48) ICBC (01398.HK)

(49) XIAOMI-W (01810.HK)

(50) BUD APAC (01876.HK)

(51) SANDS CHINA LTD (01928.HK)

(52) CHOW TAI FOOK (01929.HK)

(53) WHARF REIC (01997.HK)

(54) COUNTRY GARDEN (02007.HK)

(55) ANTA SPORTS (02020.HK)

(56) WUXI BIO (02269.HK)

(57) SHENZHOU INTL (02313.HK)

(58) PING AN (02318.HK)

(59) MENGNIU DAIRY (02319.HK)

(60) LI NING (02331.HK)

(61) SUNNY OPTICAL (02382.HK)

(62) BOC HONG KONG (02388.HK)

(63) CHINA LIFE (02628.HK)

(64) ENN ENERGY (02688.HK)

(65) MEITUAN-W (03690.HK)

(66) HANSOH PHARMA (03692.HK)

(67) CM BANK (03968.HK)

(68) BANK OF CHINA (03988.HK)

(69) CG SERVICES (06098.HK)

(70) HAIER SMARTHOME (06690.HK)

(71) HAIDILAO (06862.HK)

(72) JD-SW (09618.HK)

(73) NONGFU SPRING (09633.HK)

(74) BIDU-SW (09888.HK)

(75) BABA-SW (09988.HK)

(76) NTES-S (09999.HK)

In [5]:
yfin.pdr_override()
stocks3 = ['0001.HK', '0002.HK', '0003.HK', '0005.HK', '0006.HK', '0011.HK', '0012.HK', '0016.HK', '0017.HK', '0027.HK', '0066.HK', '0101.HK', '0175.HK', '0241.HK', \
          '0267.HK', '0288.HK', '0291.HK', '0316.HK', '0322.HK', '0386.HK', '0388.HK', '0669.HK', '0688.HK', '0700.HK', '0762.HK', '0823.HK', '0857.HK', '0868.HK', '0881.HK', '0883.HK', \
           '0939.HK', '0941.HK', '0960.HK', '0968.HK', '0981.HK', '0992.HK', '1038.HK', '1044.HK', '1088.HK', '1093.HK', '1109.HK', '1113.HK', '1177.HK', '1209.HK', '1211.HK', \
           '1299.HK', '1378.HK', '1398.HK', '1810.HK', '1876.HK', '1928.HK', '1929.HK', '1997.HK', '2007.HK', '2020.HK', '2269.HK', '2313.HK', '2318.HK', '2319.HK', '2331.HK', \
           '2382.HK', '2388.HK', '2628.HK', '2688.HK', '3690.HK', '3692.HK', '3968.HK', '3988.HK', '6098.HK', '6690.HK', '6862.HK', '9618.HK', '9633.HK', '9888.HK', '9988.HK', '9999.HK']
ls_key = 'Adj Close' 
ls_key_data = []
for stock in stocks3:
  df_hang_original = web.get_data_yahoo(stock,start,end)
  ls_key_data.append(df_hang_original[ls_key])

df_hang = pd.DataFrame(columns = stocks3)
for i in range(len(stocks3)):
  stock = stocks3[i]
  df_hang[stock] = ls_key_data[i]

# We drop the stocks which don't have 10-year's historical data, if one stock doesn't have sufficient 10-year data then the first data would be np.nan. 
# We drop this stock based on this judgement.
for j in df_hang.columns:
  if np.isnan(df_hang[j][0]) == True:
    df_hang = df_hang.drop(j,axis = 1)

df_hang

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

,0001.HK,0002.HK,0003.HK,0005.HK,0006.HK,0011.HK,0012.HK,0016.HK,0017.HK,0027.HK,...,2313.HK,2318.HK,2319.HK,2331.HK,2382.HK,2388.HK,2628.HK,2688.HK,3968.HK,3988.HK
Date,,,,,,,,,,,,,,,,,,,,,
2013-01-23 00:00:00+08:00,57.709270,42.863209,7.839488,52.487041,32.618969,81.902306,19.889170,82.506775,32.549019,30.935465,...,15.308767,27.644835,10.936888,5.498331,5.566259,17.353304,20.627018,31.854307,12.759558,2.010596
2013-01-24 00:00:00+08:00,58.519543,42.994793,7.876123,52.672394,32.867401,82.638962,19.958054,83.790916,33.392715,31.115061,...,15.585850,27.368582,10.821275,5.498331,5.766354,17.255627,20.395689,31.598112,12.759558,2.010596
2013-01-25 00:00:00+08:00,58.384499,42.961895,7.894440,53.444714,32.991623,83.375587,20.147470,83.405685,33.437115,30.890568,...,15.932202,27.092331,10.659417,4.692617,5.920972,17.223074,19.778805,32.793716,12.541910,1.999958
2013-01-28 00:00:00+08:00,57.979359,43.093472,7.894440,53.938992,33.090992,84.313156,20.130255,83.020432,32.904263,30.396679,...,16.157330,27.309391,10.682541,4.559807,5.748164,17.353304,19.971582,32.494808,12.637129,2.015916
2013-01-29 00:00:00+08:00,57.709270,43.356640,8.040971,53.908104,33.240047,84.313156,19.975273,82.570976,32.504612,30.800772,...,16.191965,27.171263,10.936888,4.701471,5.893686,17.418421,19.855915,31.939711,12.514704,2.015916
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-01-16 00:00:00+08:00,50.349998,57.400002,7.660000,56.650002,43.799999,128.000000,28.850000,108.599998,22.950001,54.150002,...,103.000000,60.799999,37.849998,69.000000,99.449997,27.650000,14.900000,124.400002,48.900002,2.980000
2023-01-17 00:00:00+08:00,49.500000,57.250000,7.570000,56.650002,43.750000,127.300003,28.900000,109.199997,22.950001,52.950001,...,99.250000,59.349998,37.150002,70.000000,101.800003,27.049999,14.420000,123.400002,49.500000,2.970000
2023-01-18 00:00:00+08:00,49.500000,57.500000,7.620000,56.799999,43.900002,128.000000,29.200001,109.800003,22.650000,54.900002,...,99.250000,60.200001,36.849998,69.849998,104.300003,26.900000,14.680000,125.199997,48.700001,2.960000
2023-01-19 00:00:00+08:00,49.400002,57.650002,7.610000,56.650002,44.299999,127.500000,29.500000,110.300003,22.900000,54.349998,...,101.599998,60.450001,37.099998,72.550003,105.400002,26.950001,14.740000,123.800003,49.650002,2.960000
2023-01-20 00:00:00+08:00,49.700001,58.000000,7.680000,56.900002,43.950001,128.199997,29.650000,111.599998,23.650000,54.900002,...,101.800003,62.150002,37.500000,74.400002,106.900002,27.200001,15.020000,124.099998,50.650002,2.990000

In [6]:
# Save the generated Hang Seng data

df_hang.to_csv('/content/drive/MyDrive/JPMorgan/自写代码/TensorFlow_codes/Stock_datas/hang_seng_data.csv')

Next, after the saving of the dataframes, we can read these .csv files

In [4]:
df_dow = pd.read_csv('/content/drive/MyDrive/JPMorgan/自写代码/TensorFlow_codes/Stock_datas/dow30_data.csv') 
df_stoxx = pd.read_csv('/content/drive/MyDrive/JPMorgan/自写代码/TensorFlow_codes/Stock_datas/stoxx50_data.csv')
df_hang = pd.read_csv('/content/drive/MyDrive/JPMorgan/自写代码/TensorFlow_codes/Stock_datas/hang_seng_data.csv')

In [18]:
# We only keep the year-month-day format

for i in range(len(df_dow['Date'])):
  df_dow['Date'][i] = df_dow['Date'][i][:10]

for i in range(len(df_stoxx['Date'])):
  df_stoxx['Date'][i] = df_stoxx['Date'][i][:10]

for i in range(len(df_hang['Date'])):
  df_hang['Date'][i] = df_hang['Date'][i][:10]

<ipython-input-18-1d0e52b7165d>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_dow['Date'][i] = df_dow['Date'][i][:10]
<ipython-input-18-1d0e52b7165d>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_stoxx['Date'][i] = df_stoxx['Date'][i][:10]
<ipython-input-18-1d0e52b7165d>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_hang['Date'][i] = df_hang['Date'][i][:10]

In [20]:
df_dow

,Date,axp,amgn,aapl,ba,cat,cvx,csco,ko,gs,...,nke,pg,crm,trv,unh,vz,v,wba,wmt,dis
0,2013-01-23,51.051556,64.127632,15.787227,62.254250,73.055481,76.055046,15.086039,27.105648,122.984039,...,23.758392,52.821320,42.605000,61.582092,47.942154,27.051653,37.082523,29.898703,55.654442,49.045559
1,2013-01-24,51.372082,63.780235,13.836589,63.117359,72.866875,76.379059,15.378686,27.091053,122.477066,...,24.102970,52.619556,43.072498,61.939018,48.207970,26.925205,37.201424,29.838179,55.894722,49.045559
2,2013-01-25,51.545338,64.397820,13.510408,62.874348,72.097534,76.841957,15.473795,27.047255,122.054649,...,24.859266,54.734203,43.465000,62.145233,48.053612,26.975784,37.266705,30.012180,55.262028,49.436470
3,2013-01-28,51.172848,66.072983,13.816012,62.011219,73.508087,76.736137,15.407953,27.018051,121.792732,...,24.389376,55.122765,44.517502,61.352081,47.856403,27.039005,36.453018,30.337496,55.542328,49.418289
4,2013-01-29,51.502029,66.844971,14.075237,61.717937,74.375572,77.509880,15.203096,27.317356,124.285164,...,24.129820,56.041862,43.672501,61.716934,48.259418,27.500507,36.525284,30.307226,55.974804,49.081932
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2512,2023-01-13,155.759995,271.730011,134.759995,214.130005,257.233215,177.559998,48.880001,61.430000,374.000000,...,128.850006,149.939133,149.509995,193.919998,489.570007,41.860001,223.059998,36.779999,145.289993,99.400002
2513,2023-01-17,153.750000,269.420013,135.940002,211.410004,255.043686,180.490005,48.080002,61.680000,349.920013,...,128.139999,149.501877,148.470001,185.000000,485.079987,40.849998,223.000000,36.330002,144.410004,99.910004
2514,2023-01-18,150.419998,264.390015,135.210007,209.410004,251.620010,177.229996,46.900002,59.810001,349.089996,...,126.430000,145.497009,145.449997,183.630005,476.239990,39.970001,219.460007,35.610001,140.839996,99.040001
2515,2023-01-19,146.850006,262.029999,135.270004,207.089996,245.750000,179.000000,46.459999,59.720001,350.750000,...,124.529999,142.419998,146.410004,184.039993,484.359985,40.060001,220.410004,35.410000,138.830002,99.080002
2516,2023-01-20,151.600006,263.239990,137.869995,206.759995,249.710007,180.899994,46.779999,60.080002,341.839996,...,126.620003,142.970001,151.250000,185.330002,486.720001,40.000000,224.309998,35.880001,140.539993,103.480003

In [21]:
# Save the generated completed data

df_dow.to_csv('/content/drive/MyDrive/JPMorgan/自写代码/TensorFlow_codes/Stock_datas/dow30_data_complete.csv')
df_stoxx.to_csv('/content/drive/MyDrive/JPMorgan/自写代码/TensorFlow_codes/Stock_datas/stoxx50_data_complete.csv')
df_hang.to_csv('/content/drive/MyDrive/JPMorgan/自写代码/TensorFlow_codes/Stock_datas/hang_seng_data_complete.csv')

____________________________________________________________________________________________________

Next, we divide these three dataframes into training and testing sets. For each of them, we divide it into 80% training set and 20% testing set. For each set (training or testing), we set 50 time points. Based on these 50 time points, we continue to divide the set into different batches. Then we will have the consistent format three-dimension tensor (batch number, time points number, stock number).

____________________________________________________________________________________________________

In [5]:
# Read the completed dataframes

df_dow = pd.read_csv('/content/drive/MyDrive/JPMorgan/自写代码/TensorFlow_codes/Stock_datas/dow30_data_complete.csv')
df_stoxx = pd.read_csv('/content/drive/MyDrive/JPMorgan/自写代码/TensorFlow_codes/Stock_datas/stoxx50_data_complete.csv')
df_hang = pd.read_csv('/content/drive/MyDrive/JPMorgan/自写代码/TensorFlow_codes/Stock_datas/hang_seng_data_complete.csv')

In [6]:
df_hang.columns

Index(['Unnamed: 0', 'Date', '0001.HK', '0002.HK', '0003.HK', '0005.HK',
       '0006.HK', '0011.HK', '0012.HK', '0016.HK', '0017.HK', '0027.HK',
       '0066.HK', '0101.HK', '0175.HK', '0241.HK', '0267.HK', '0291.HK',
       '0316.HK', '0322.HK', '0386.HK', '0388.HK', '0669.HK', '0688.HK',
       '0700.HK', '0762.HK', '0823.HK', '0857.HK', '0868.HK', '0881.HK',
       '0883.HK', '0939.HK', '0941.HK', '0960.HK', '0981.HK', '0992.HK',
       '1038.HK', '1044.HK', '1088.HK', '1093.HK', '1109.HK', '1177.HK',
       '1211.HK', '1299.HK', '1378.HK', '1398.HK', '1928.HK', '1929.HK',
       '2007.HK', '2020.HK', '2313.HK', '2318.HK', '2319.HK', '2331.HK',
       '2382.HK', '2388.HK', '2628.HK', '2688.HK', '3968.HK', '3988.HK'],
      dtype='object')

In [7]:
df_dow = df_dow.drop('Unnamed: 0',axis = 1)
df_stoxx = df_stoxx.drop('Unnamed: 0',axis = 1)
df_hang = df_hang.drop('Unnamed: 0',axis = 1)

[For Dow 30]:

In [8]:
df_dow_train = df_dow[:round(len(df_dow)*0.8)].reset_index()
df_dow_train = df_dow_train.drop('index',axis = 1)
df_dow_train

,Date,axp,amgn,aapl,ba,cat,cvx,csco,ko,gs,...,nke,pg,crm,trv,unh,vz,v,wba,wmt,dis
0,2013-01-23,51.051556,64.127632,15.787227,62.254250,73.055481,76.055046,15.086039,27.105648,122.984039,...,23.758392,52.821320,42.605000,61.582092,47.942154,27.051653,37.082523,29.898703,55.654442,49.045559
1,2013-01-24,51.372082,63.780235,13.836589,63.117359,72.866875,76.379059,15.378686,27.091053,122.477066,...,24.102970,52.619556,43.072498,61.939018,48.207970,26.925205,37.201424,29.838179,55.894722,49.045559
2,2013-01-25,51.545338,64.397820,13.510408,62.874348,72.097534,76.841957,15.473795,27.047255,122.054649,...,24.859266,54.734203,43.465000,62.145233,48.053612,26.975784,37.266705,30.012180,55.262028,49.436470
3,2013-01-28,51.172848,66.072983,13.816012,62.011219,73.508087,76.736137,15.407953,27.018051,121.792732,...,24.389376,55.122765,44.517502,61.352081,47.856403,27.039005,36.453018,30.337496,55.542328,49.418289
4,2013-01-29,51.502029,66.844971,14.075237,61.717937,74.375572,77.509880,15.203096,27.317356,124.285164,...,24.129820,56.041862,43.672501,61.716934,48.259418,27.500507,36.525284,30.307226,55.974804,49.081932
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2009,2021-01-14,120.791862,227.230988,127.380882,209.910004,188.023087,87.579483,42.533924,46.353996,294.781403,...,138.754639,128.453201,215.600006,136.254150,341.298859,51.479382,199.121368,45.405006,142.430481,173.429993
2010,2021-01-15,119.201210,230.832291,125.631866,204.320007,185.375153,84.461151,42.797699,45.854965,288.213104,...,138.185089,127.488365,213.139999,137.134903,342.048584,51.786236,198.855011,45.036751,140.172455,171.440002
2011,2021-01-19,123.690163,233.446289,126.313690,210.710007,185.825226,86.680672,42.571606,45.676064,281.692596,...,136.761200,126.372208,216.759995,137.393387,342.915161,51.488407,198.924072,44.327881,138.961075,172.259995
2012,2021-01-20,125.827309,237.292099,130.463882,211.449997,184.178177,87.478592,42.712910,45.836132,278.121155,...,140.227615,124.792542,223.440002,138.839050,341.600708,51.677929,203.215012,44.272640,141.015564,173.639999
2013,2021-01-21,124.353745,236.981796,135.246429,207.410004,184.034546,84.387772,42.496239,46.090363,277.067902,...,139.059067,124.669807,222.169998,142.381332,345.651093,51.686958,202.356857,43.333607,140.375977,171.279999

In [9]:
df_dow_test = df_dow[round(len(df_dow)*0.8):].reset_index()
df_dow_test = df_dow_test.drop('index',axis = 1)
df_dow_test

,Date,axp,amgn,aapl,ba,cat,cvx,csco,ko,gs,...,nke,pg,crm,trv,unh,vz,v,wba,wmt,dis
0,2021-01-22,123.094894,238.364059,137.420380,205.839996,183.795135,84.130966,42.175941,45.657234,277.087067,...,136.839767,123.708679,225.770004,139.624084,338.397339,51.867462,199.279190,43.683445,141.810257,172.779999
1,2021-01-25,118.225357,241.749069,141.224686,203.360001,179.390366,83.369720,42.420879,45.930286,271.007019,...,135.072189,125.840294,225.919998,140.121918,338.650513,52.724846,198.253296,44.024075,141.684265,171.889999
2,2021-01-26,113.346062,243.159531,141.461823,202.059998,179.265884,81.957314,42.637550,46.410500,269.781464,...,132.666336,126.649132,226.259995,137.584885,334.074219,51.055195,199.269318,45.285316,142.953812,169.559998
3,2021-01-27,111.335793,236.069702,140.374878,194.029999,172.965118,80.893394,43.052059,45.694893,261.709808,...,128.659821,122.167084,224.779999,133.554321,324.220734,49.755577,192.324860,47.117352,139.397156,163.029999
4,2021-01-28,116.097992,232.957336,135.463837,197.229996,176.517670,81.645462,42.712910,46.278675,263.327942,...,132.293198,124.051270,226.500000,134.033020,329.244843,49.972179,195.530762,46.657047,139.309937,171.880005
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
498,2023-01-13,155.759995,271.730011,134.759995,214.130005,257.233215,177.559998,48.880001,61.430000,374.000000,...,128.850006,149.939133,149.509995,193.919998,489.570007,41.860001,223.059998,36.779999,145.289993,99.400002
499,2023-01-17,153.750000,269.420013,135.940002,211.410004,255.043686,180.490005,48.080002,61.680000,349.920013,...,128.139999,149.501877,148.470001,185.000000,485.079987,40.849998,223.000000,36.330002,144.410004,99.910004
500,2023-01-18,150.419998,264.390015,135.210007,209.410004,251.620010,177.229996,46.900002,59.810001,349.089996,...,126.430000,145.497009,145.449997,183.630005,476.239990,39.970001,219.460007,35.610001,140.839996,99.040001
501,2023-01-19,146.850006,262.029999,135.270004,207.089996,245.750000,179.000000,46.459999,59.720001,350.750000,...,124.529999,142.419998,146.410004,184.039993,484.359985,40.060001,220.410004,35.410000,138.830002,99.080002
502,2023-01-20,151.600006,263.239990,137.869995,206.759995,249.710007,180.899994,46.779999,60.080002,341.839996,...,126.620003,142.970001,151.250000,185.330002,486.720001,40.000000,224.309998,35.880001,140.539993,103.480003

In [10]:
# We adjust the dimensions of both the training and testing sets, from 1-D to 3-D:
# We split the original training and testing sets into equal-length fragments. By this way, each fragment has 50 or 51 time points and we just take the first 50 time points as the time series. 
# For the training set , there are 2014 rows so we split it into 40 fragments then each fragment has 50 or 51 time points.
# For the testing set , there are 503 rows so we split it into 10 fragments then each fragment has 50 or 51 time points.

dow_data_train = []
for i in range(len(np.array_split(df_dow_train.iloc[:,1:],40))):  
  batch_group = []
  for ii in range(len(np.array_split(df_dow_train.iloc[:,1:],40)[i])):
    batch_group.append(list(np.array_split(df_dow_train.iloc[:,1:],40)[i].iloc[ii]))
  batch_group = np.array(batch_group[:50])  # We just take the first 50 rows as 50 time points. By this way, we can ensure all arrays have the same dimensions: (50, 29) in one batch
  dow_data_train.append(np.array(batch_group.reshape((50,len(np.array_split(df_dow_train.iloc[:,1:],40)[i].columns)))))

dow_data_test = []
for i in range(len(np.array_split(df_dow_test.iloc[:,1:],10))):  
  batch_group = []
  for ii in range(len(np.array_split(df_dow_test.iloc[:,1:],10)[i])):
    batch_group.append(list(np.array_split(df_dow_test.iloc[:,1:],10)[i].iloc[ii]))
  batch_group = np.array(batch_group[:50])  # We just take the first 50 rows as 50 time points. By this way, we can ensure all arrays have the same dimensions: (50, 29) in one batch
  dow_data_test.append(np.array(batch_group.reshape((50,len(np.array_split(df_dow_test.iloc[:,1:],10)[i].columns)))))

In [11]:
# The the 3 dimensions are correct:
# 40 or 10 batches, 50 time points, 29 features (stocks)

print(np.array(dow_data_train).shape)
print(np.array(dow_data_test).shape)

(40, 50, 29)
(10, 50, 29)

In [12]:
np.save('/content/drive/MyDrive/JPMorgan/自写代码/TensorFlow_codes/Stock_datas/dow_data_train.npy',dow_data_train)
np.save('/content/drive/MyDrive/JPMorgan/自写代码/TensorFlow_codes/Stock_datas/dow_data_test.npy',dow_data_test)

[For Stoxx 50]:

In [13]:
df_stoxx_train = df_stoxx[:round(len(df_stoxx)*0.8)].reset_index()
df_stoxx_train = df_stoxx_train.drop('index',axis = 1)
df_stoxx_train

,Date,BUD,ASML,BAYZF,BBVA,CRH,E,IBDRY,IDEXY,ING,LIN,LVMUY,NOK,PRNDY,SAN,SAP,STLA,TTFNF
0,2013-01-23,70.186897,62.611176,73.488098,6.486995,15.476578,29.142651,13.439261,11.278678,6.522679,90.535728,27.143465,3.646603,20.270298,5.326166,66.550735,2.601512,37.866943
1,2013-01-24,70.295929,64.374489,73.298210,6.588650,16.136135,29.086239,13.602848,11.278678,6.596954,90.821823,27.550247,3.347959,20.453667,5.363498,66.449158,2.717532,37.866943
2,2013-01-25,71.425201,66.951637,73.298210,6.696662,16.320194,29.221621,14.043269,11.380891,6.677981,91.320366,28.104946,3.300804,20.712048,5.481720,68.556908,2.771079,38.826237
3,2013-01-28,71.503098,68.244743,77.361877,6.645834,16.258846,29.238550,13.804186,11.046736,6.779265,89.890053,27.994011,3.340100,20.378653,5.456831,68.023628,2.833552,38.335770
4,2013-01-29,72.616791,68.063881,75.417389,6.607711,16.381556,28.302109,13.967772,10.936660,6.765760,90.355927,28.134533,3.308664,20.695375,5.438165,68.751595,2.860325,39.165234
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2009,2021-01-14,68.111206,534.783875,59.686764,4.651258,42.391289,19.403275,53.285816,14.919872,8.208928,255.942139,119.238731,4.053792,36.485546,3.236534,120.523521,14.429122,40.689117
2010,2021-01-15,67.413887,517.944641,59.239040,4.541168,42.154366,18.640818,52.597965,14.742032,8.140091,250.506699,116.354164,4.043880,36.090851,3.113508,119.472168,13.717571,39.903419
2011,2021-01-19,67.119247,539.546021,60.022552,4.513647,42.647179,18.816093,52.763050,14.713952,8.028228,251.428772,116.295883,4.093438,36.495171,3.113508,121.460190,15.203715,39.294270
2012,2021-01-20,67.079964,539.428223,60.535568,4.531995,42.893581,19.008900,52.533764,14.929233,8.165904,249.836960,119.976868,4.162817,36.052341,3.094581,121.985855,15.356836,40.318340
2013,2021-01-21,66.598709,560.401306,59.882637,4.513647,42.144886,18.500593,52.139393,14.882432,8.140091,245.760376,120.530479,4.182640,36.110100,3.056727,122.243927,15.095634,39.550285

In [14]:
df_stoxx_test = df_stoxx[round(len(df_stoxx)*0.8):].reset_index()
df_stoxx_test = df_stoxx_test.drop('index',axis = 1)
df_stoxx_test

,Date,BUD,ASML,BAYZF,BBVA,CRH,E,IBDRY,IDEXY,ING,LIN,LVMUY,NOK,PRNDY,SAN,SAP,STLA,TTFNF
0,2021-01-22,65.420151,559.134644,59.556175,4.476950,41.889004,18.360374,52.331993,14.657792,8.054042,244.090897,121.909630,4.162817,35.907936,2.971555,121.842499,14.546210,39.126534
1,2021-01-25,63.544266,557.328003,58.427547,4.394383,40.960247,17.930941,52.387024,14.245952,7.701247,245.682724,119.452393,4.807063,35.561367,2.895846,123.897430,13.933739,37.396210
2,2021-01-26,63.976410,539.055115,58.931236,4.412732,40.600117,18.132511,51.809227,14.330192,7.907762,248.332504,123.347061,4.688126,36.148605,2.924237,128.915253,14.059835,39.135365
3,2021-01-27,62.326416,515.126587,56.506081,4.220076,39.330177,18.009813,50.341797,14.114912,7.511944,235.772705,117.597351,6.492013,35.436230,2.772820,126.344215,13.510412,38.508560
4,2021-01-28,63.858547,537.307373,57.755966,4.394383,40.391613,18.299025,50.809544,14.311471,7.795901,242.207901,121.627975,4.648479,36.755093,2.848529,124.671608,13.960760,38.067146
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
498,2023-01-13,60.919998,659.690002,62.110001,6.890000,45.639999,31.450001,47.369999,14.940000,13.700000,334.109985,171.000000,5.030000,42.110001,3.370000,117.010002,15.420000,63.990002
499,2023-01-17,61.070000,658.190002,61.740002,6.930000,45.330002,31.129999,47.049999,14.910000,13.430000,330.000000,171.470001,4.820000,42.459999,3.330000,116.209999,15.450000,64.849998
500,2023-01-18,59.290001,652.289978,60.439999,6.880000,44.720001,30.990000,46.430000,14.860000,13.230000,324.339996,172.050003,4.780000,41.040001,3.330000,117.080002,15.280000,64.250000
501,2023-01-19,59.330002,630.250000,60.250000,6.810000,44.439999,31.219999,46.959999,14.690000,13.200000,324.540009,168.309998,4.680000,41.799999,3.290000,115.669998,15.130000,62.959999
502,2023-01-20,59.799999,648.849976,60.750000,6.910000,45.009998,31.709999,47.220001,14.900000,13.380000,328.619995,170.020004,4.610000,41.689999,3.350000,117.120003,15.200000,62.990002

In [15]:
# We adjust the dimensions of both the training and testing sets, from 1-D to 3-D:
# We split the original training and testing sets into equal-length fragments. By this way, each fragment has 50 or 51 time points and we just take the first 50 time points as the time series. 
# For the training set , there are 2014 rows so we split it into 40 fragments then each fragment has 50 or 51 time points.
# For the testing set , there are 503 rows so we split it into 10 fragments then each fragment has 50 or 51 time points.

stoxx_data_train = []
for i in range(len(np.array_split(df_stoxx_train.iloc[:,1:],40))):  
  batch_group = []
  for ii in range(len(np.array_split(df_stoxx_train.iloc[:,1:],40)[i])):
    batch_group.append(list(np.array_split(df_stoxx_train.iloc[:,1:],40)[i].iloc[ii]))
  batch_group = np.array(batch_group[:50])  # We just take the first 50 rows as 50 time points. By this way, we can ensure all arrays have the same dimensions: (50, 29) in one batch
  stoxx_data_train.append(np.array(batch_group.reshape((50,len(np.array_split(df_stoxx_train.iloc[:,1:],40)[i].columns)))))

stoxx_data_test = []
for i in range(len(np.array_split(df_stoxx_test.iloc[:,1:],10))):  
  batch_group = []
  for ii in range(len(np.array_split(df_stoxx_test.iloc[:,1:],10)[i])):
    batch_group.append(list(np.array_split(df_stoxx_test.iloc[:,1:],10)[i].iloc[ii]))
  batch_group = np.array(batch_group[:50])  # We just take the first 50 rows as 50 time points. By this way, we can ensure all arrays have the same dimensions: (50, 29) in one batch
  stoxx_data_test.append(np.array(batch_group.reshape((50,len(np.array_split(df_stoxx_test.iloc[:,1:],10)[i].columns)))))

In [16]:
# The the 3 dimensions are correct:
# 40 or 10 batches, 50 time points, 17 features (stocks)

print(np.array(stoxx_data_train).shape)
print(np.array(stoxx_data_test).shape)

(40, 50, 17)
(10, 50, 17)

In [17]:
np.save('/content/drive/MyDrive/JPMorgan/自写代码/TensorFlow_codes/Stock_datas/stoxx_data_train.npy',stoxx_data_train)
np.save('/content/drive/MyDrive/JPMorgan/自写代码/TensorFlow_codes/Stock_datas/stoxx_data_test.npy',stoxx_data_test)

[For Hang Seng]:

In [18]:
df_hang_train = df_hang[:round(len(df_hang)*0.8)].reset_index()
df_hang_train = df_hang_train.drop('index',axis = 1)
df_hang_train

,Date,0001.HK,0002.HK,0003.HK,0005.HK,0006.HK,0011.HK,0012.HK,0016.HK,0017.HK,...,2313.HK,2318.HK,2319.HK,2331.HK,2382.HK,2388.HK,2628.HK,2688.HK,3968.HK,3988.HK
0,2013-01-23,57.709270,42.863209,7.839488,52.487041,32.618969,81.902306,19.889170,82.506775,32.549019,...,15.308767,27.644835,10.936888,5.498331,5.566259,17.353304,20.627018,31.854307,12.759558,2.010596
1,2013-01-24,58.519543,42.994793,7.876123,52.672394,32.867401,82.638962,19.958054,83.790916,33.392715,...,15.585850,27.368582,10.821275,5.498331,5.766354,17.255627,20.395689,31.598112,12.759558,2.010596
2,2013-01-25,58.384499,42.961895,7.894440,53.444714,32.991623,83.375587,20.147470,83.405685,33.437115,...,15.932202,27.092331,10.659417,4.692617,5.920972,17.223074,19.778805,32.793716,12.541910,1.999958
3,2013-01-28,57.979359,43.093472,7.894440,53.938992,33.090992,84.313156,20.130255,83.020432,32.904263,...,16.157330,27.309391,10.682541,4.559807,5.748164,17.353304,19.971582,32.494808,12.637129,2.015916
4,2013-01-29,57.709270,43.356640,8.040971,53.908104,33.240047,84.313156,19.975273,82.570976,32.504612,...,16.191965,27.171263,10.936888,4.701471,5.893686,17.418421,19.855915,31.939711,12.514704,2.015916
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1967,2021-01-15,51.852993,65.970505,10.022484,39.643105,36.587200,135.918137,28.087225,94.009392,31.016260,...,140.913223,93.399597,46.902157,50.205750,187.678238,22.497711,15.815010,118.013229,57.372791,2.314511
1968,2021-01-18,52.126625,65.924561,9.986942,38.812397,36.631866,134.145691,28.400797,93.922829,30.973598,...,139.944733,91.950134,47.638069,52.627094,201.660538,22.314056,15.815010,118.400162,56.619125,2.314511
1969,2021-01-19,53.084332,66.613663,10.040253,40.427658,37.167942,136.198029,29.251928,96.519775,31.656210,...,149.145248,92.040726,47.098400,54.060131,217.612213,22.589539,16.083975,118.013229,57.278584,2.348423
1970,2021-01-20,52.673885,66.797424,9.915860,39.920002,36.989254,134.332275,29.117537,94.961601,31.741541,...,151.566452,91.678360,48.373981,54.356621,215.642868,22.359970,16.191559,115.401474,57.561203,2.356901
1971,2021-01-21,52.491463,67.348724,10.040253,40.935310,37.033928,136.664413,29.296724,94.961601,31.997520,...,150.501114,91.044228,47.196522,51.490543,215.248993,22.589539,16.317076,117.529572,58.456184,2.356901

In [19]:
df_hang_test = df_hang[round(len(df_hang)*0.8):].reset_index()
df_hang_test = df_hang_test.drop('index',axis = 1)
df_hang_test

,Date,0001.HK,0002.HK,0003.HK,0005.HK,0006.HK,0011.HK,0012.HK,0016.HK,0017.HK,...,2313.HK,2318.HK,2319.HK,2331.HK,2382.HK,2388.HK,2628.HK,2688.HK,3968.HK,3988.HK
0,2021-01-22,51.533760,66.797424,10.022484,39.873856,36.944580,134.238968,28.938353,94.355652,31.656210,...,149.920029,88.326477,45.430332,49.909260,212.885788,22.314056,15.599842,122.462914,55.535732,2.297555
1,2021-01-25,50.074398,66.246147,9.915860,39.504654,36.542526,133.306122,28.714373,93.576569,31.357573,...,158.055237,89.141808,46.754978,50.650486,218.006058,22.084486,15.528118,121.785789,56.760437,2.314511
2,2021-01-26,50.393631,66.613663,9.898090,38.950851,36.721214,132.279968,28.714373,93.922829,31.485561,...,151.275894,87.012917,46.705914,49.810432,210.719513,21.900833,15.277087,119.367493,56.195187,2.280599
3,2021-01-27,51.168915,67.716232,9.915860,39.458500,36.944580,132.653107,29.117537,94.009392,31.485561,...,151.372742,86.967621,45.724697,48.278561,212.294983,21.946747,15.241224,120.818466,56.572018,2.314511
4,2021-01-28,50.302418,67.532486,9.951401,38.350895,36.944580,134.145691,28.535191,92.884048,31.144251,...,145.271347,84.612244,45.234089,46.944351,197.918793,21.579441,14.936399,120.238075,56.195187,2.272120
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
488,2023-01-16,50.349998,57.400002,7.660000,56.650002,43.799999,128.000000,28.850000,108.599998,22.950001,...,103.000000,60.799999,37.849998,69.000000,99.449997,27.650000,14.900000,124.400002,48.900002,2.980000
489,2023-01-17,49.500000,57.250000,7.570000,56.650002,43.750000,127.300003,28.900000,109.199997,22.950001,...,99.250000,59.349998,37.150002,70.000000,101.800003,27.049999,14.420000,123.400002,49.500000,2.970000
490,2023-01-18,49.500000,57.500000,7.620000,56.799999,43.900002,128.000000,29.200001,109.800003,22.650000,...,99.250000,60.200001,36.849998,69.849998,104.300003,26.900000,14.680000,125.199997,48.700001,2.960000
491,2023-01-19,49.400002,57.650002,7.610000,56.650002,44.299999,127.500000,29.500000,110.300003,22.900000,...,101.599998,60.450001,37.099998,72.550003,105.400002,26.950001,14.740000,123.800003,49.650002,2.960000
492,2023-01-20,49.700001,58.000000,7.680000,56.900002,43.950001,128.199997,29.650000,111.599998,23.650000,...,101.800003,62.150002,37.500000,74.400002,106.900002,27.200001,15.020000,124.099998,50.650002,2.990000

In [20]:
# We adjust the dimensions of both the training and testing sets, from 1-D to 3-D:
# We split the original training and testing sets into equal-length fragments. By this way, each fragment has 50 or 51 time points and we just take the first 50 time points as the time series. 
# For the training set , there are 1972 rows so we split it into 39 fragments then each fragment has 50 or 51 time points.
# For the testing set , there are 493 rows so we split it into 9 fragments then each fragment has 54 or 55 time points.

hang_data_train = []
for i in range(len(np.array_split(df_hang_train.iloc[:,1:],39))):  
  batch_group = []
  for ii in range(len(np.array_split(df_hang_train.iloc[:,1:],39)[i])):
    batch_group.append(list(np.array_split(df_hang_train.iloc[:,1:],39)[i].iloc[ii]))
  batch_group = np.array(batch_group[:50])  # We just take the first 50 rows as 50 time points. By this way, we can ensure all arrays have the same dimensions: (50, 29) in one batch
  hang_data_train.append(np.array(batch_group.reshape((50,len(np.array_split(df_hang_train.iloc[:,1:],39)[i].columns)))))

hang_data_test = []
for i in range(len(np.array_split(df_hang_test.iloc[:,1:],9))):  
  batch_group = []
  for ii in range(len(np.array_split(df_hang_test.iloc[:,1:],9)[i])):
    batch_group.append(list(np.array_split(df_hang_test.iloc[:,1:],9)[i].iloc[ii]))
  batch_group = np.array(batch_group[:50])  # We just take the first 50 rows as 50 time points. By this way, we can ensure all arrays have the same dimensions: (50, 29) in one batch
  hang_data_test.append(np.array(batch_group.reshape((50,len(np.array_split(df_hang_test.iloc[:,1:],9)[i].columns)))))

In [21]:
# The the 3 dimensions are correct:
# 39 or 9 batches, 50 time points, 58 features (stocks)

print(np.array(hang_data_train).shape)
print(np.array(hang_data_test).shape)

(39, 50, 58)
(9, 50, 58)

In [22]:
np.save('/content/drive/MyDrive/JPMorgan/自写代码/TensorFlow_codes/Stock_datas/hang_data_train.npy',hang_data_train)
np.save('/content/drive/MyDrive/JPMorgan/自写代码/TensorFlow_codes/Stock_datas/hang_data_test.npy',hang_data_test)

Next we check out the mismatching dates between: 

(1) Dow 30 and Stoxx 50 (check again, Dow → Stoxx and Dow ← Stoxx)

(2) Dow 30 and Hang Seng (check again, Dow → Hang Seng and Dow ← Hang Seng)

(3) Stoxx 50 and Hang Seng (check again, Stoxx → Hang Seng and Stoxx ← Hang Seng)

In [19]:
# 1.1 Dow 30 → Stoxx 50
for i in range(len(df_dow)):
  if df_dow['Date'][i] not in list(df_stoxx['Date']):
    print(df_dow['Date'][i])

In [21]:
# 1.2 Dow 30 ← Stoxx 50
for i in range(len(df_stoxx)):
  if df_stoxx['Date'][i] not in list(df_dow['Date']):
    print(df_stoxx['Date'][i])

No any mismatching above

In [23]:
# 2.1 Dow 30 → Hang Seng
dow_hang_mismatch = []
for i in range(len(df_dow)):
  if df_dow['Date'][i] not in list(df_hang['Date']):
    dow_hang_mismatch.append(df_dow['Date'][i])
    print(df_dow['Date'][i])

print(len(dow_hang_mismatch))

2013-02-11
2013-02-12
2013-02-13
2013-04-01
2013-04-04
2013-05-01
2013-05-17
2013-06-12
2013-07-01
2013-09-20
2013-10-01
2013-10-14
2013-12-26
2014-01-31
2014-02-03
2014-04-21
2014-05-01
2014-05-06
2014-06-02
2014-07-01
2014-09-09
2014-10-01
2014-10-02
2014-12-26
2015-02-19
2015-02-20
2015-04-06
2015-04-07
2015-05-01
2015-07-01
2015-09-03
2015-09-28
2015-10-01
2015-10-21
2016-02-08
2016-02-09
2016-02-10
2016-03-28
2016-04-04
2016-05-02
2016-06-09
2016-07-01
2016-09-16
2016-10-10
2016-12-27
2017-01-30
2017-01-31
2017-04-04
2017-04-17
2017-05-01
2017-05-03
2017-05-30
2017-10-02
2017-10-05
2017-12-26
2018-02-16
2018-04-02
2018-04-05
2018-05-01
2018-05-22
2018-06-18
2018-07-02
2018-09-25
2018-10-01
2018-10-17
2018-12-26
2019-02-05
2019-02-06
2019-02-07
2019-04-05
2019-04-22
2019-05-01
2019-05-13
2019-06-07
2019-07-01
2019-10-01
2019-10-07
2019-12-26
2020-01-27
2020-01-28
2020-04-13
2020-04-30
2020-05-01
2020-06-25
2020-07-01
2020-10-01
2020-10-02
2020-10-13
2020-10-26
2021-02-12
2021-04-05
2021-04-06
2021-05-19
2021-06-14
2021-07-01
2021-09-22
2021-10-01
2021-10-13
2021-10-14
2021-12-27
2022-02-01
2022-02-02
2022-02-03
2022-04-05
2022-04-18
2022-05-02
2022-05-09
2022-06-03
2022-07-01
2022-09-12
2022-10-04
2022-12-27
112

112 mismatching dates above

In [24]:
# 2.2 Dow 30 ← Hang Seng
hang_dow_mismatch = []
for i in range(len(df_hang)):
  if df_hang['Date'][i] not in list(df_dow['Date']):
    hang_dow_mismatch.append(df_hang['Date'][i])
    print(df_hang['Date'][i])

print(len(hang_dow_mismatch))

2013-02-18
2013-05-27
2013-07-04
2013-09-02
2013-11-28
2014-01-20
2014-02-17
2014-05-26
2014-07-04
2014-09-01
2014-11-27
2015-01-19
2015-02-16
2015-07-03
2015-09-07
2015-11-26
2016-01-18
2016-02-15
2016-05-30
2016-07-04
2016-09-05
2016-11-24
2017-01-16
2017-02-20
2017-05-29
2017-07-04
2017-09-04
2017-11-23
2018-01-15
2018-05-28
2018-07-04
2018-09-03
2018-11-22
2018-12-05
2019-01-21
2019-02-18
2019-05-27
2019-07-04
2019-09-02
2019-11-28
2020-01-20
2020-02-17
2020-05-25
2020-07-03
2020-09-07
2020-11-26
2021-01-18
2021-05-31
2021-07-05
2021-09-06
2021-11-25
2021-12-24
2022-01-17
2022-02-21
2022-05-30
2022-06-20
2022-07-04
2022-09-05
2022-11-24
2023-01-16
60

60 mismatching dates above

As we have confirmed that Dow 30 and Stoxx 50 have same dates so actually we don't need to do the following checks.

In [25]:
# 3.1 Stoxx 50 → Hang Seng
stoxx_hang_mismatch = []
for i in range(len(df_stoxx)):
  if df_stoxx['Date'][i] not in list(df_hang['Date']):
    stoxx_hang_mismatch.append(df_stoxx['Date'][i])
    print(df_stoxx['Date'][i])

print(len(stoxx_hang_mismatch))

2013-02-11
2013-02-12
2013-02-13
2013-04-01
2013-04-04
2013-05-01
2013-05-17
2013-06-12
2013-07-01
2013-09-20
2013-10-01
2013-10-14
2013-12-26
2014-01-31
2014-02-03
2014-04-21
2014-05-01
2014-05-06
2014-06-02
2014-07-01
2014-09-09
2014-10-01
2014-10-02
2014-12-26
2015-02-19
2015-02-20
2015-04-06
2015-04-07
2015-05-01
2015-07-01
2015-09-03
2015-09-28
2015-10-01
2015-10-21
2016-02-08
2016-02-09
2016-02-10
2016-03-28
2016-04-04
2016-05-02
2016-06-09
2016-07-01
2016-09-16
2016-10-10
2016-12-27
2017-01-30
2017-01-31
2017-04-04
2017-04-17
2017-05-01
2017-05-03
2017-05-30
2017-10-02
2017-10-05
2017-12-26
2018-02-16
2018-04-02
2018-04-05
2018-05-01
2018-05-22
2018-06-18
2018-07-02
2018-09-25
2018-10-01
2018-10-17
2018-12-26
2019-02-05
2019-02-06
2019-02-07
2019-04-05
2019-04-22
2019-05-01
2019-05-13
2019-06-07
2019-07-01
2019-10-01
2019-10-07
2019-12-26
2020-01-27
2020-01-28
2020-04-13
2020-04-30
2020-05-01
2020-06-25
2020-07-01
2020-10-01
2020-10-02
2020-10-13
2020-10-26
2021-02-12
2021-04-05
2021-04-06
2021-05-19
2021-06-14
2021-07-01
2021-09-22
2021-10-01
2021-10-13
2021-10-14
2021-12-27
2022-02-01
2022-02-02
2022-02-03
2022-04-05
2022-04-18
2022-05-02
2022-05-09
2022-06-03
2022-07-01
2022-09-12
2022-10-04
2022-12-27
112

In [26]:
# 3.2 Stoxx 50 ← Hang Seng
hang_stoxx_mismatch = []
for i in range(len(df_hang)):
  if df_hang['Date'][i] not in list(df_stoxx['Date']):
    hang_stoxx_mismatch.append(df_hang['Date'][i])
    print(df_hang['Date'][i])

print(len(hang_stoxx_mismatch))

2013-02-18
2013-05-27
2013-07-04
2013-09-02
2013-11-28
2014-01-20
2014-02-17
2014-05-26
2014-07-04
2014-09-01
2014-11-27
2015-01-19
2015-02-16
2015-07-03
2015-09-07
2015-11-26
2016-01-18
2016-02-15
2016-05-30
2016-07-04
2016-09-05
2016-11-24
2017-01-16
2017-02-20
2017-05-29
2017-07-04
2017-09-04
2017-11-23
2018-01-15
2018-05-28
2018-07-04
2018-09-03
2018-11-22
2018-12-05
2019-01-21
2019-02-18
2019-05-27
2019-07-04
2019-09-02
2019-11-28
2020-01-20
2020-02-17
2020-05-25
2020-07-03
2020-09-07
2020-11-26
2021-01-18
2021-05-31
2021-07-05
2021-09-06
2021-11-25
2021-12-24
2022-01-17
2022-02-21
2022-05-30
2022-06-20
2022-07-04
2022-09-05
2022-11-24
2023-01-16
60